---
version: 0.2

phases:
  build:
    commands:
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version
      - curl -qL -o aws_credentials.json http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - aws s3 sync aws s3://solodev-aws-ha/aws --delete
      - aws s3 sync legacy s3://solodev-aws-ha/legacy --delete
      - DATE=$(date +%d%H%M)
      
      - echo "Delete Old Stacks"
      - chmod 700 bin/cleanStacks.sh bin/stacks.sh
      # - ./bin/cleanStacks.sh
      - ./bin/stacks.sh
      - echo "Cleanup" | rm -f *json
  post_build:
    commands:
      - echo "S3 synced on `date`"