Description: >
    Backup Plan template to back up all resources tagged with specified key=value daily at 5am UTC.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    BackupSelectionName:
        Description: A Backup Selection Name that appears in the backup plan
        Type: String
        Default: ""  

    BackupTagKey:
        Description: The associated tag key with the backup plan
        Type: String
        Default: "" 

    BackupTagValue:
        Description: The associated tag value with the backup plan
        Type: String
        Default: ""                           

Resources:

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Encryption key for daily"
      EnableKeyRotation: True
      Enabled: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              "AWS": { "Fn::Sub": "arn:${AWS::Partition}:iam::${AWS::AccountId}:root" }
            Action:
              - kms:*
            Resource: "*"

  BackupVault:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: !Ref 'EnvironmentName'
      EncryptionKeyArn: !GetAtt KMSKey.Arn

  BackupPlan:
    Type: "AWS::Backup::BackupPlan"
    Properties:
      BackupPlan:
        BackupPlanName: !Ref 'EnvironmentName'
        BackupPlanRule:
          -
            RuleName: "DailyBackups"
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: "cron(0 5 ? * * *)"
            Lifecycle:
              DeleteAfterDays: 35

    DependsOn: BackupVault

  BackupSelectionByTags:
    Type: AWS::Backup::BackupSelection
    DependsOn: BackupPlan
    Properties:
      BackupSelection: 
        SelectionName: !Ref BackupSelectionName
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWSBackupDefaultServiceRole"
        ListOfTags:
          - 
            ConditionType: "STRINGEQUALS"
            ConditionKey: !Ref BackupTagKey
            ConditionValue: !Ref BackupTagValue
      BackupPlanId: !Ref BackupPlan    